"""initial schema

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2024-01-15 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_estudiante', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('carrera', sa.String(length=100), nullable=True),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_estudiante'),
    sa.UniqueConstraint('email')
    )
    op.create_table('libros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('editorial', sa.String(length=100), nullable=True),
    sa.Column('año_publicacion', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('ejemplares_totales', sa.Integer(), nullable=True),
    sa.Column('ejemplares_disponibles', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prestamo', sa.DateTime(), nullable=False),
    sa.Column('fecha_devolucion_esperada', sa.DateTime(), nullable=False),
    sa.Column('fecha_devolucion_real', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos')
    op.drop_table('libros')
    op.drop_table('estudiantes')
    # ### end Alembic commands ###